package com.playwin.ads

enum class RewardType {
    QUIZ_LIFELINE,
    SPIN,
    DAILY_TASK,
    BONUS_COINS,
    PROFILE_REWARD,
    BLOCK_MASTER_CONTINUE,
    BLOCK_MASTER_DOUBLE_REWARD,
    BLOCK_MASTER_EXTRA_COINS,
    BLOCK_MASTER_POWERUP
}
