package com.myplaywin.app.shadowhero.engine

import kotlin.math.max
import kotlin.math.min

/**
 * Parameters generated by ShadowHeroDifficultyDirector to guide
 * procedural section and chunk generation.
 */
data class ChunkDifficultyParams(
    val baseStage: Int,
    val effectiveDifficulty: Float,       // Base stage + adaptive modifier
    val adaptiveModifier: Float,          // Range: -1.5f to +1.5f
    val gapWidthMultiplier: Float,        // Multiplier on jump gaps (0.7f to 1.3f)
    val platformWidthMultiplier: Float,   // Multiplier on platform sizes (0.8f to 1.3f)
    val hazardDensityMultiplier: Float,   // Density of spikes, blades, lasers (0.5f to 1.4f)
    val enemyDensityMultiplier: Float,    // Density of AI enemies (0.5f to 1.4f)
    val verticalityFactor: Float,         // Vertical climb frequency (0.8f to 1.4f)
    val riskRouteProbability: Float,      // Probability of optional risk/reward routes
    val secretRoomProbability: Float,     // Probability of secret rooms (~0.05f to 0.12f)
    val needsRecoverySection: Boolean     // True if player has failed repeatedly
)

/**
 * ShadowHeroDifficultyDirector
 * Tracks player performance using a rolling window and dynamically adjusts difficulty
 * parameters for the procedural world generator without making jumps impossible or trivial.
 */
class ShadowHeroDifficultyDirector {

    // Rolling window metrics
    private var recentDeaths: Int = 0
    private var recentCheckpointFailures: Int = 0
    private var recentDamageTaken: Float = 0f
    private var recentCrystalsCollected: Int = 0
    private var recentCrystalsSpawned: Int = 0
    private var recentJumpsCount: Int = 0
    private var recentWallJumpsCount: Int = 0
    private var recentDashCount: Int = 0
    private var recentStageCompletionTimeSeconds: Float = 0f
    private var recentSuccessStreak: Int = 0

    // Smoothly interpolated adaptive modifier
    var currentAdaptiveModifier: Float = 0f
        private set

    fun resetSession() {
        recentDeaths = 0
        recentCheckpointFailures = 0
        recentDamageTaken = 0f
        recentCrystalsCollected = 0
        recentCrystalsSpawned = 0
        recentJumpsCount = 0
        recentWallJumpsCount = 0
        recentDashCount = 0
        recentStageCompletionTimeSeconds = 0f
        recentSuccessStreak = 0
        currentAdaptiveModifier = 0f
    }

    /**
     * Records a death event. Never drastically drops difficulty from a single death,
     * but tracks cumulative failures.
     */
    fun recordDeath(cause: String) {
        recentDeaths++
        recentCheckpointFailures++
        recentSuccessStreak = 0

        // Gradually ease difficulty if deaths accumulate
        if (recentDeaths >= 3) {
            val target = -0.4f * (recentDeaths - 2).coerceAtMost(3)
            currentAdaptiveModifier = (currentAdaptiveModifier + target * 0.3f).coerceIn(-1.5f, 1.5f)
        }
    }

    /**
     * Records damage taken by the player.
     */
    fun recordDamage(amount: Float) {
        recentDamageTaken += amount
        if (recentDamageTaken > 150f) {
            currentAdaptiveModifier = (currentAdaptiveModifier - 0.15f).coerceIn(-1.5f, 1.5f)
            recentDamageTaken = 0f
        }
    }

    /**
     * Records checkpoint reached or section cleared smoothly.
     */
    fun recordCheckpointReached(timeTaken: Float, crystalsCollected: Int, totalCrystalsInChunk: Int) {
        recentSuccessStreak++
        recentCheckpointFailures = 0
        recentCrystalsCollected += crystalsCollected
        recentCrystalsSpawned += totalCrystalsInChunk

        // If player is clearing smoothly with high crystal count, increase challenge slightly
        val crystalRatio = if (totalCrystalsInChunk > 0) crystalsCollected.toFloat() / totalCrystalsInChunk else 0.5f
        if (recentSuccessStreak >= 2 && crystalRatio > 0.7f) {
            currentAdaptiveModifier = (currentAdaptiveModifier + 0.2f).coerceIn(-1.5f, 1.5f)
        }
    }

    /**
     * Records player movement actions to gauge skill mastery.
     */
    fun recordMovementStats(jumps: Int, wallJumps: Int, dashes: Int) {
        recentJumpsCount += jumps
        recentWallJumpsCount += wallJumps
        recentDashCount += dashes

        if (recentWallJumpsCount > 5 && recentDashCount > 5) {
            // Player is mastering movement mechanics
            currentAdaptiveModifier = (currentAdaptiveModifier + 0.1f).coerceIn(-1.5f, 1.5f)
        }
    }

    /**
     * Returns the final difficulty params derived from base stage number and adaptive modifier.
     */
    fun getDifficultyParameters(baseStage: Int): ChunkDifficultyParams {
        val rawDiff = baseStage.toFloat() + currentAdaptiveModifier
        val effectiveDiff = rawDiff.coerceAtLeast(1.0f)

        // Gap multiplier: 0.85x to 1.25x
        val gapMult = (1.0f + (effectiveDiff - baseStage) * 0.1f).coerceIn(0.75f, 1.25f)

        // Platform width multiplier: 1.2x (easy) down to 0.85x (hard)
        val platMult = (1.0f - (effectiveDiff - baseStage) * 0.1f).coerceIn(0.8f, 1.3f)

        // Hazard density
        val hazardMult = (1.0f + (effectiveDiff - 1f) * 0.05f + currentAdaptiveModifier * 0.15f)
            .coerceIn(0.4f, 1.5f)

        // Enemy density
        val enemyMult = (0.8f + (effectiveDiff - 1f) * 0.04f + currentAdaptiveModifier * 0.15f)
            .coerceIn(0.3f, 1.4f)

        // Verticality
        val vertFactor = (1.0f + min(1.0f, effectiveDiff * 0.02f)).coerceIn(0.8f, 1.4f)

        // Risk route probability
        val riskProb = (0.25f + currentAdaptiveModifier * 0.1f).coerceIn(0.1f, 0.6f)

        // Secret room probability (5% - 12%)
        val secretProb = (0.08f + currentAdaptiveModifier * 0.02f).coerceIn(0.05f, 0.15f)

        // Recovery section needed if player died multiple times recently
        val recoveryNeeded = recentDeaths >= 3 || recentCheckpointFailures >= 2

        return ChunkDifficultyParams(
            baseStage = baseStage,
            effectiveDifficulty = effectiveDiff,
            adaptiveModifier = currentAdaptiveModifier,
            gapWidthMultiplier = gapMult,
            platformWidthMultiplier = platMult,
            hazardDensityMultiplier = hazardMult,
            enemyDensityMultiplier = enemyMult,
            verticalityFactor = vertFactor,
            riskRouteProbability = riskProb,
            secretRoomProbability = secretProb,
            needsRecoverySection = recoveryNeeded
        )
    }
}
